#!/usr/bin/env node
/**
 * Build script to generate config.js from .env file
 * This runs before TypeScript compilation to inject environment variables
 */

const fs = require('fs');
const path = require('path');

// Read .env file
const envPath = path.join(__dirname, '..', '.env');
const envVars = {};

if (fs.existsSync(envPath)) {
    const envContent = fs.readFileSync(envPath, 'utf8');
    
    // Parse .env file
    envContent.split('\n').forEach(line => {
        line = line.trim();
        if (line && !line.startsWith('#')) {
            const [key, ...valueParts] = line.split('=');
            if (key && valueParts.length > 0) {
                envVars[key.trim()] = valueParts.join('=').trim();
            }
        }
    });
}

// Generate config.ts file
const configContent = `// This file is auto-generated from .env by build-config.js
// Do not edit this file directly

export const config = {
    ANTHROPIC_API_KEY: '${envVars.ANTHROPIC_API_KEY || ''}',
    // Add other environment variables as needed
} as const;

export type Config = typeof config;
`;

// Write config file
const configPath = path.join(__dirname, '..', 'src', 'config.ts');
fs.writeFileSync(configPath, configContent);

console.log('✓ Generated src/config.ts from .env');